### ISSUE TITLE
Feature request: Additional highlight groups

### ISSUE THREAD

**Issue by modille** [mjswensen/themer-vim#1]
First of all -- awesome job on themer, themer-gui, and themer-vim! 👏 

I think it would be nice to add more highlight groups so that syntax highlighting is even better for more languages/plugins.

base16-vim has a bunch that could be used for reference:
https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache

When I have more time then I'll be happy to contribute here, but I figured I'd open an issue in case anyone can get to it sooner.

**Comment by mjswensen** [comment]
Thanks, @modille! I agree, it's pretty vanilla as it stands now—I totally would not be opposed to the addition of more highlight groups. Thanks for logging the issue. I'll assign the "help wanted" label for now, and if you or anyone else would like to jump on this feel free to update this thread. 👍

**Comment by mjswensen** [comment]
@modille , I am moving this repository over to a multi-package repo under [mjswensen/themer](https://github.com/mjswensen/themer)—feel free to re-open over there if desired!
